---
- name: Secure remote host and configure cloud native workshop
  hosts: workstation
  vars_files:
    - roles/cloud-native-workshop/defaults/main.yml

  tasks:

    - name: create users yaml
      template:
        src: roles/cloud-native-workshop/templates/users.j2
        dest: /tmp/users.yml
        mode: '0400'
