---
# Create file with list of users. 
- name: Make sure file exists
  file:
    path: files/users.yml
    state: present
  delegate_to: localhost

- name: Create list of users
  template:
    src: templates/users.j2
    dest: files/users.yml
  delegate_to: localhost