---
- name: Detect the hosts ssh port
  import_tasks: detect_ssh_port.yml

- name: Security hardening of the host
  import_tasks: security.yml

- name: Create list of users
  import_tasks: create_users_list.yml

- name: Setup workshop environment
  import_tasks: setup_workshop.yml